### PR TITLE
[WIP] Europa Station job conversion

### LINKED ISSUE #40: Most jobs do not spawn with required equipment.

### PR DESCRIPTION
**Pull request by Loganbacca**
- Resolves #40

Still very much work in progress, but thought I'd throw this up here for visibility and input.

Todo:
- [ ] Write a todo list

### CODE REVIEW

**Comment by Zuhayr** [comment]
Couple of little things -
New code needs to go into the modules/europa folder if possible to minimize conflicts.
Synths are going to be government at least initially rather than civilian.

**Comment by Loganbacca** [comment]
No problem, I'll shift all the new job defines and the like to the europa folder.

For all the existing Bay job code scattered throughout the codebase, should I leave them in? i.e. use the existing ```command_positions``` list for head jobs?

**Comment by Zuhayr** [comment]
Might be a good idea unless there's a pressing reason not to/

**Comment by Zuhayr** [comment]
Had a look over the code and this is a better way to do it.

**Comment by Zuhayr** [comment]
Working on this myself since we're in a hurry and you seem to have vanished :(

**Comment by Loganbacca** [comment]
No worries, got distracted by real life.

I'll pitch in again when I find time to.

**Comment by Zuhayr** [comment]
No worries!

**Pull request merged**
