### PR TITLE
Mapathon Updates.

### PR DESCRIPTION
**Pull request by WrongEnd**
Read commit message for changelog. Pictures coming when they upload.

### CODE REVIEW

**Comment by WrongEnd** [comment]
http://i.gyazo.com/287426e12becf2d92582855cddefe12d.png
http://i.gyazo.com/f340f5d79901965ebe9e0d3cdf8fe583.png
http://i.gyazo.com/dd02c2741f2f8cd511da4b0cac69ad77.png
http://i.gyazo.com/30eedcf27d7988d0a37d6edfa3477359.png
http://i.gyazo.com/add56f3bdfea7667df2a2f9162827178.png
http://i.gyazo.com/414617492a0327f938399e113f306c5f.png

**Comment by PJB3005** [comment]
OH GOD DIAGONAL WIRES PLEASE NO

**Comment by Nienhaus** [comment]
Mapper Friend: it has a lot of open space. the bar area seems especially large.
Mapper Friend: also: diagonol wires. gross.
Mapper Friend: aside from that, it's fine.

**Comment by SkowronX** [comment]
Ya gotta fix ALL the diagonal wires now.

**Comment by WrongEnd** [comment]
If the wires prove to be a problem, I'll switch them out, but as of current they should transfer power fine and also look great. I've also tried to keep things small -- Botany is large because it's a dome, and the bar if a bit spacier because I'm trying to make it a good central meeting area. The bar is also the most well lit area on the map, fitting in with the 'Central meeting area and safest place on the dome' theme I'm trying to push.

**Comment by Zuhayr** [comment]
Wires tend to look a lot better when restricted to cardinals imo. The large curving arcs look untidy.

**Comment by WrongEnd** [comment]
Waiting until I can have someone test the map for bugs.

**Comment by Dennok** [comment]
What engine on this map?

**Comment by PJB3005** [comment]
Probably something geothermal if I had to guess.

Of course I'm gonna suggest the R-UST :^)

**Comment by WrongEnd** [comment]
Currently a placeholder magical engine that automagically produces power.

**Comment by GinjaNinja32** [comment]
RUST was removed from Baycode due to being broken, don't even know if it still exists here, probably not.

**Comment by SkyMarshal** [comment]
That thing was a monstrosity.

**Comment by SkowronX** [comment]
1. There are a few rogue seafloors hiding under a few doors. They can be easily located by seeing if a door has a blue overlay.
2. The SMES have power but do not charge the apcs because the wires have no direct connection to their terminals.
3. Diagonal hallways are going to be pretty iffy design wise since they're just a series of zig zags.
4. I suggest adding more lights so I don't have to keep spawning floodlights and mesons to check things. You can delete them later if you intend on dimming for effect later on.

**Comment by PJB3005** [comment]
@GinjaNinja32 then we fix it!

**Comment by Zuhayr** [comment]
Stop pushing for the RUST, it isn't happening.

**Comment by Zuhayr** [comment]
https://github.com/Yonaguni/EuropaStation/pull/62

**Pull request closed without merging**
