### PR TITLE
510 lighting system.

### PR DESCRIPTION
**Pull request by Zuhayr**
Very WIP!

image

image

**TODO:**
- [x] Lit objects in other objects leave their lighting overlay behind when the container moves.
- [x] Directional lights and different light edge softness would be good.
- [x] Light range may be too small currently.
- [x] Need to remove a bunch of stubs from the previous lighting system.
- [ ] Need to add a non-dynamic lighting area overlay.
- [ ] Lots of little TODO cleanup stuff scattered around.
- [ ] Reimplement turf-based lighting.
- [ ] Other shit that I will find or remember.

### CODE REVIEW

**Comment by comma** [comment]
> Light range may be too small currently.

Yeah, seems like it's on par with using PDA light currently

**Comment by Zuhayr** [comment]
image
Softer lights (also with flicker)

**Comment by Zuhayr** [comment]
With Logan's much improved lighting icon:
image
image

**Comment by Zuhayr** [comment]
Major issues currently:
- [ ] Blindness causes the client dir to change and the screen to rotate (???).
- [ ] Lights bleed through walls.
- [ ] SEE_PIXELS causes things like offset APCS to be visible through walls.
- [ ] Ghosts cannot see their darkness overlay, resulting in weird foggy lights (which are kinda cool but weird).
- [ ] Lots of objects in storage are set to the incorrect plane (utility belts) causing them to show up beneath the UI slot.

**Comment by Loganbacca** [comment]
Perhaps we could do turf shadow casting for static lights only? 

I believe tg have some code for handling pixel offset objects, and possibly also for catching clicks that should be blocked.

**Comment by Nienhaus** [comment]
:+1: :x: :100:

**Comment by Zuhayr** [comment]
- GUI bugs fixed other than a purely visual one with storage slots that I can't chase down.
- Rotating view bug is due to a MASTER_PLANE overlay being inside the mob, KEEP_APART does nothing, kind of at a loss for fixing it. Related to 510, may be a bug.
- Light bleed is fine for now. Fixing it is going to involve serverside icon clipping which may be fiddly and not strictly -needed-.
- Using bound_width and bound_height to make it possible to check a turf contents for light levels resulted in chess mode. r i p.

**Comment by Zuhayr** [comment]
Going to go ahead and merge this now for live testing, #yolo.

**Pull request merged**
