### PR TITLE
Chinsky's gun stuff. + surgery

### PR DESCRIPTION
**Pull request by Zuhayr**
WIP work on surgery, pushing to try and fix some runtime issues on the main server.

````
Using an object containing disinfectant (acid, ethanol or antiseptics) on a person will disinfect the target limb.
Upgrading to an aggressive grab will not pin the person. This is done by switching to harm intent with a grab while targeting chest.
Advanced medical kits have been removed.
You must be resting and not starving or dehydrated to naturally heal brute and burn damage.
Bandaging and salving wounds do not actually reduce wound severity; rather they remove status effects (bleeding, infection chance) and allow them to heal.
Wounds can be reduced by sewing them shut.
Large wounds cannot be bandaged and must be sewn shut first.
Surgery now requires an open cutting wound (an incision) to count as open. 
This means that if you bandage someone's chest mid-surgery you're going to have to cut them open again.
You no longer need to retract the skin around the wound post-incision.
Any bone fracture will constitute an open ribcage (rather than explicitly a surgery result).
Fractures will no longer reapply if the organ is too damaged post-setting.

Basic surgery is now:

- Scalpel to make an incision, if they have no other open wounds.
	- Cautery to stop bleeding.
	- Hemostat to remove implants or shrapnel.
- Saw to break open the skull or ribcage, if it isn't already broken.
	- Sutures to repair internal organ damage.
- Bone setter to put the broken bone back in place.
- Bone gel to repair the break.
- Sutures to close the wound up.
- Bandages if needed.
- Food, water and rest to heal the damage.

Ways to get wound data:
	Grab-inspect:
		- Dead/alive.
		- Wounds.
		- Fractures.
		- Internal bleeding.
		- Implants.
		- Cavities.
		- Necrosis.
		- Internal cavity.
		- General toxloss.
		- General oxyloss.
	Flashlight to eyes:
		- Eye damage/eye blurriness.
		- Blindness.
		- Drug use (morphine).
		- Brain damage.
		- Brain worms.
````

### CODE REVIEW

**Comment by Finalsong** [comment]
:+1: :100: :heart:

**Comment by Nienhaus** [comment]
@Finalsong No hype in PRs pls

**Comment by NobleCaos** [comment]
No one can stop @Finalsong 's hypetrain

**Comment by Finalsong** [comment]
it's an impossible task, yes

**Pull request merged**
