### PR TITLE
Various fixes/remaps tram

### PR DESCRIPTION
**Pull request by Vivalas**
Fixes an oversight with trams causing the ones mapped into glitch, reworks tram lines. etc.

Trams now work as intended, mostly. The two ones mapped in now work and I did some few minor changes to them.

I will possibly look at adding lighting to trams (red lights to warn people as tram comes, anyone?) Also the rails are no longer centered and I can fix that if needed.

Dunno why map changes are so large, I ran mapmerge.

### CODE REVIEW

**Comment by WrongEnd** [comment]
Grrr, github won't show me the changes to the map file. Gonna have to :-1: this until the reason why the changes are so massive are figured out.

**Comment by Vivalas** [comment]
I could uh, try to run mapmerge again, not sure how that voodoo works.

**Comment by GinjaNinja32** [comment]
my guess is mapmerge broke

**Comment by Zuhayr** [comment]
This isn't going to get merged without being cleaned.

**Comment by Zuhayr** [comment]
#252

**Pull request closed without merging**
