### PR TITLE
Map changes, wiring and lighting added to civ section near tram

### PR DESCRIPTION
**Pull request by NobleCaos**
Feedback appreciated.
civ south wired and lit

### CODE REVIEW

**Comment by NobleCaos** [comment]
Errors noticed, fixing now.

**Comment by NobleCaos** [comment]
civ south wired and lit
Problems solved, lighting and wire are now functional.

**Comment by Zuhayr** [comment]
Layers > untick 'Area' > tick 'only show selectable layers'.

**Comment by NobleCaos** [comment]
civ south wired and lit no layer overlay

**Pull request merged**
