### PR TITLE
Implements basic water_act() behavior for machines

### PR DESCRIPTION
**Pull request by Vivalas2**
I went through also and set the new waterproof var as appropriate for each machine, so tell me if you think some things need to be waterproof/not waterproof etc. Machines are waterproof by default.

Also checks to see if power is on before damaging the machine.

### CODE REVIEW

**Comment by Vivalas2** [comment]
image

**Comment by Vivalas2** [comment]
Dunno what's causing the conflict.

**Comment by Vivalas2** [comment]
Screw you commits. Be gone!

**Comment by mwerezak** [comment]
Have you considered making waterproof a flag?

**Comment by Vivalas2** [comment]
Not really, I don't think it's necessary IMO, and the multiple-state waterproof var is usefull.

**Comment by Yonaguni** [comment]
Don't mind me, just dicking around.

**Pull request merged**
