### PR TITLE
Slash and burn.

### PR DESCRIPTION
**Pull request by Zuhayr**
Removes xenoarchaeology, R&D, origin_tech and slimes. 

Also removes golems, slime extracts and a leftover xenomorph definition.

RIP AND TEAR.

- Adds the ability to set an output direction for autolathes.
- Adds a queue system to autolathes.
image
- Breaks the autolathe up into several machines descending from the same basic machine (reusing a bunch of science icons.
image

- New general conduit system (very barebones and buggy currently)
image

- Matter feed and matter bins for fabricators (no more lathes).
image

- Example layout (data and matter feeds!)
image

image

### CODE REVIEW

**Comment by NobleCaos** [comment]
RIP Science, we will never forget. Quick, someone merge this so we can get better science!

**Comment by Zuhayr** [comment]
Working well, as far as I can tell.

**Comment by Dennok** [comment]
Fire destructors! Fire manchism-scienctism!

**Comment by Zuhayr** [comment]
Note to self: fix matter multiplier value causing free steel sheets.

**Comment by Loganbacca** [comment]
Nice, nice, and more nice.
Especially the removing xenoarch bit.

**Pull request merged**
