### PR TITLE
Adds atmos room

### PR DESCRIPTION
**Pull request by Minijar**
Due to git being a horrible person to me, I can't use the map merge tool as it just causes conflicts for some reason.

### CODE REVIEW

**Comment by NobleCaos** [comment]
Pictures please

**Comment by NobleCaos** [comment]
Someone else judge that... My atmos skills are worse than anything ever. But it looks good, and it passed the checks

**Comment by PsiOmegaDelta** [comment]
While perhaps assable I doubt it'll ever get merged without cleanup.

**Comment by Minijar** [comment]
@PsiOmegaDelta You'll have to take it from my fork then. Since mapmerge just buggers everything for me.

**Comment by NobleCaos** [comment]
Remove the phoron tanks from the top

**Comment by GinjaNinja32** [comment]
Floor coloring isn't great for making modifications, which pretty much every atmos tech is gonna want to make.
I assume that's a waste tank on the right? Would be nice to have a way to get gas out of it, however unlikely it may be.
Canister-filling ports for all tanks, too, please.

**Comment by Minijar** [comment]
I'll remove the phoron canisters, there's only a Co2 tank, Air tank and a nitrogen. Then a empty mixing tank and waste tank.

**Comment by NobleCaos** [comment]
Looks good.

**Comment by NobleCaos** [comment]
I don't have the ability to merge... and it looks just as nasty as it should. Maybe add blast doors to all of them?

**Comment by Dennok** [comment]
No noo. no blast doors to all, one push button and all station with out oxygen (in atmos ( but now no one gasp on hours after off atmos it hermetic rooms)).
And this left top valves, now it cant be unwrenched. Better change it to standard valves or pumps.

**Comment by Zuhayr** [comment]
I will merge this if you pull/resolve the map conflicts (there shouldn't be overlaps, it's just Git being dumb).

This design can be altered down the track, having any atmospherics mapped at all will be an improvement on nothing.

**Comment by Dorsisdwarf** [comment]
I'm going to drop in to suggest rearranging the gas canister storage to allow you to shrink the room down a teeny bit.

**Comment by Vivalas** [comment]
Just a thought, shouldn't there be water storage/dump/waste tanks or something?

**Comment by Zuhayr** [comment]
Is this going to get updated?

**Comment by Minijar** [comment]
Not until this weekend unfortunately.

**Comment by Zuhayr** [comment]
Fixing this myself.

**Pull request closed without merging**
