### PR TITLE
[DNM] Mecha rewrite.

### PR DESCRIPTION
**Pull request by Zuhayr**
leg day
new HUD
new mechs

WIP
- [x] Add mech HUD.
- [x] Add mech construction.
- [x] Add modular mech icons/weapon overlays.
- [ ] Work out why mechs can't attack windows.
- [ ] Readd mech software/circuits.
- [x] Readd internal atmospherics.
- [ ] Readd internal radio.
- [ ] Readd control consoles/beacons.
- [x] Add life/death.
- [x] Add wreckage and salvaging.
- [ ] Add emp_act(), stun, sleep, paralysis handling.
- [ ] Reimplement all tools and weapons.
- [ ] Reimplement the means of producing mech parts.
- [x] Finalize and polish up the construction process.
- [ ] Convert other mech models to the system.
- [ ] Add sounds to the construction deconstruction stuff.
- [ ] Test test test test test.

### CODE REVIEW

**Comment by WrongEnd** [comment]
Daaamn. Talk about hardcore dedication to cleaning up code.

**Comment by Zuhayr** [comment]
Having a job would be so nice.

**Comment by GinjaNinja32** [comment]
Any plans to port/PR this to Bay once it's complete?

**Comment by Zuhayr** [comment]
No, but it will be trivial to do so.

**Comment by GinjaNinja32** [comment]
excellent

**Comment by DerptheStewpidGoat** [comment]
I'm only slightly familiar with this project but this one PR really hypes me up. Good work guys.

**Comment by Zuhayr** [comment]
#201

**Pull request closed without merging**
