### PR TITLE
Re-added geothermals attempt 2

### PR DESCRIPTION
**Pull request by NobleCaos**
ntugzfq

dxegomg

### CODE REVIEW

**Comment by Zuhayr** [comment]
Christ those are ugly. I need to work out a better structure for the engines.

:+1:&&travis

**Comment by NobleCaos** [comment]
@Zuhayr Are you complaining about my system or the look of the geothermals themselves?

**Comment by Zuhayr** [comment]
Your system is as good as could be expected, I'm talking about the way you have to arrange the engines to make them function.

**Comment by NobleCaos** [comment]
Do you actually have to arrange the engines like this? I did this because it looks nice than when they're right on top of each other...

**Comment by Zuhayr** [comment]
If you add them right next to each other, the icons link up and they form one solid machine.

**Pull request merged**
