### PR TITLE
Map changes, geothermal engines, mining fix, and area change.

### PR DESCRIPTION
**Pull request by NobleCaos**

### CODE REVIEW

**Comment by NobleCaos** [comment]
Someone add a Do Not Merge to this

**Comment by NobleCaos** [comment]
http://i.imgur.com/NViFpMW.png
http://i.imgur.com/i1C6FVm.png
http://i.imgur.com/5yw3PD2.png

Map issues solved, ready to merge.

**Comment by NobleCaos** [comment]
One of you remove the "Do not merge", please.

**Comment by NobleCaos** [comment]
It's also ready to merge.. once someone has taken a look at it t make sure I haven't fucked it up

**Comment by Zuhayr** [comment]
#yolo

**Pull request merged**
