### PR TITLE
Adds a preliminary Government dome

### PR DESCRIPTION
**Pull request by Vivalas2**
Not full of items yet, but it's all there and mostly outlined/complete. Needs AI Core/Upload and telecomms.

### CODE REVIEW

**Comment by Vivalas2** [comment]
WrongEnd1 also wanted me to commit his update to the map

**Comment by WrongEnd** [comment]
Thanks, Vivalas.
:+1:

**Comment by Zuhayr** [comment]
Screenshots?

**Comment by WrongEnd** [comment]
http://i.gyazo.com/ffe32a4780b85b1be52c5ec1c7378b75.png

Best I can get atm. You'll have to ask Vivalas for govdome screenshots.

**Comment by Vivalas2** [comment]
image



image


image

**Pull request merged**
