### PR TITLE
First shot at tram line and extends testing area.

### PR DESCRIPTION
**Pull request by WrongEnd**
http://i.gyazo.com/2955b4ec4b4123def81030def3071b22.png
http://i.gyazo.com/460e908b6ef900fba600935c7b612de8.png
http://i.gyazo.com/e2b49a4bbedcfb9253eaab9691adf987.png

### CODE REVIEW

**Comment by Nienhaus** [comment]
Looks pretty cool. :+1:

**Comment by mwerezak** [comment]
No doors on the tram?

**Comment by PJB3005** [comment]
@mwerezak, I don't think tram code supports that

**Comment by PJB3005** [comment]
I'm not a fan THAT IT ISN'T SYMETRICAL OH GOD

**Comment by WrongEnd** [comment]
PJB, I know, I'm hoping placing two tram tracks side by side is possible just to fix that

**Comment by mwerezak** [comment]
@PJB3005 Looks like you're right. Though, it wouldn't be hard to add in the future.

**Comment by PJB3005** [comment]
FYI: if you do ``

**Comment by SkowronX** [comment]
Getting some dead space vibes here. Love it.

**Comment by Vivalas2** [comment]
I dunno what's going on with trams, maybe you configured it wrong, or maybe it doesn't like your asymetrical design, but the tram on the main map seems a bit glitched, and the one on the testing map seems to work as intended. Don't know what's going on, but you might want to consider making it a 5 wide tram.

**Comment by WrongEnd** [comment]
At this point, I'm just going to commit it as it is, and let you work on it. I have no idea what I'm doing when it comes to trams.

**Comment by SkowronX** [comment]
Is this ready to be merged?

**Comment by Zuhayr** [comment]
Yeah I left it for Travis yesterday and forgot.

**Pull request merged**
