### PR TITLE
Replacing the SQL setup with native BYOND sqlite calls.

### PR DESCRIPTION
**Pull request by Zuhayr**
- Switches everything over to inbuilt BYOND datums.
- Removes the player privacy poll.
- Unifies all databases.
- Edits the schema/table naming conventions to remove arbitrary erro. Sorry errorage.
- Removes the legacy ban and alien whitelist systems. sqlite is DM-native, no reason not to use it.
- Unifies all the 'use legacy x' and 'enable sql y' options under 'sql_enabled'. SQL read/write is not that costly as-implemented and if you have one you might as well have them all. This can be revisited down the track.
- This is NOT backwards-compatible, do not use this if you want to keep your bans.

**TODO**
- [x] Test admin rank loading/permissions.
- [x] Test alien whitelist.
- [x] Gut the old ban system and refactor the database ban/jobban system interface.
- [ ] Reimplement bans.
- [ ] Test bans.
- [ ] Reimplement jobbans.
- [ ] Test jobbbans.
- [x] Test player age and data tracking.
- [x] Work out how sqlite can get an integer number of days for player age.
- [x] Test death tracking.
- [x] Work out why death tracking is stripping first and last characters from values.
- [x] Reimplement sanitizeSQL().
- [x] Test feedback tracking.
- [ ] Reimplement feedback tracking.
- [ ] Convert playernotes to a database table.
- [ ] Test playernotes.

### CODE REVIEW

**Comment by Zuhayr** [comment]
I know fuck all about databases/SQL and am having a hard time getting this to work, if anyone better at  SQL than me would be willing to look at the CREATE TABLE queries and let me know how I'm fucking up, that would be good.

**Comment by GinjaNinja32** [comment]
Can I suggest ditching sanitizeSQL() in favor of just using prepared statements?

This from [here](https://github.com/Yonaguni/EuropaStation/pull/397/files#diff-fab812af19bacdaadca95a24258fd2ebR90):
```dm
// sanitisation etc
var/database/query/check_query = new("INSERT INTO admin VALUES ('[ckey]', '[rank]', [rights]);")
check_query.Execute(global_db)
```
becomes this:
```dm
// ckey/rank/rights do NOT need sanitisation here; that's handled by sqlite
var/database/query/check_query = new("INSERT INTO admin VALUES (?, ?, ?);", ckey, rank, rights)
check_query.Execute(global_db)
```

**Comment by Zuhayr** [comment]
I don't know if or when I'm going to get time to look at this.

**Comment by Zuhayr** [comment]
Reopened/updated #415 following this repo becoming a 'normal' one instead of a fork.

**Pull request closed without merging**
