### PR TITLE
Fixes several lighting issues.

### PR DESCRIPTION
**Pull request by Zuhayr**
- Fixes the transformation issues resulting from images with PLANE_MASTER in a mob.
- Fixes the clickthrough when resting.
- Adds basic light bleed masking.
- Does not fix ghost vision.

### CODE REVIEW

**Comment by Zuhayr** [comment]
Bleed looks preeeetty weird now, but it's an improvement.
http://i.imgur.com/pd6IfNV.png

**Comment by comma** [comment]
Maybe make overlays trapezoid instead of rectangle? Would make it look less weird around corners imo

**Comment by PJB3005** [comment]
@comma sadly fancy shadows are gonna require prerendering to be feasible.

I'm working on a script for it though (just need to not suck at trigonometry)

**Comment by comma** [comment]
I don't mean *fancy* shadows, just trapezoid icon instead of rectangle. At fanciest, just adding the slope when 'corner' is detected, so no overlap between adjacent trapezoids

**Comment by Zuhayr** [comment]
I swear to god I will get this working eventually.

**Comment by Zuhayr** [comment]
image
It's a space rave!

**Comment by Zuhayr** [comment]
Finally getting somewhere.
image
image

**Comment by Zuhayr** [comment]
Still a lot of issues, but:

image
image

I think this is probably good enough for now considering this is a fix PR.

**Comment by Zuhayr** [comment]
image

**Comment by PJB3005** [comment]
:+1: :x: :100:

**Comment by Zuhayr** [comment]
Last one for tonight. Buggy but shows the intent.
image

**Comment by Loganbacca** [comment]
A
W
E
S
O
M
E

:+1: 
:x: 
:100:

**Comment by Zuhayr** [comment]
Look how -fucking pretty the Europa map is now-.
image

**Comment by PJB3005** [comment]
I NEED THIS IN MY LIFE.

**Comment by Loganbacca** [comment]
Awwww yeahhhhh... so atmospheric.

**Comment by PJB3005** [comment]
happening

**Pull request merged**
