### PR TITLE
Ocean fixes

### PR DESCRIPTION
**Pull request by Zuhayr**

### CODE REVIEW

**Comment by Nienhaus** [comment]
:-1:

**Comment by Zuhayr** [comment]
:100:

**Comment by Nienhaus** [comment]
:+1:

**Comment by WrongEnd** [comment]
:+1:

**Comment by SkowronX** [comment]
weee doggy

**Comment by Zuhayr** [comment]
````
zuhayr@ECHIDNA /d/Development/Yonaguni (master)
$ md5sum yonaguni.int
d2362e3e81213689d5affbe5b55f2687 *yonaguni.int
````

Literally no reason for this to fail.

**Comment by SkowronX** [comment]
4 penis heads

**Comment by PsiOmegaDelta** [comment]
According to my md5sum checker it should now have the value: 3ef44160a5c9931f1b83db8a9b6c393c

**Pull request merged**
