### PR TITLE
Updates from Polaris, updates from Baycode, added sneks.

### PR DESCRIPTION
**Pull request by Zuhayr**
Merged with Baydev.
Ported various species code.
Added SNAKE PEOPLE. They can ride motorbikes. These guys are my concession to a fey mood that resulted in making them today.

image

The tail is an overlay that follows them around, looks fine on straight lines when moving slowly, looks weird as hell with a very long tail or when turning sharp corners or changing direction a lot. Video: https://dl.dropboxusercontent.com/u/16913760/europa/2016-02-16_09-15-32.mp4

Sprites are WIP pending better ones.

### CODE REVIEW

**Comment by Finalsong** [comment]
goddamn 4rries

**Comment by Zuhayr** [comment]
In case people come across this thread and get outraged, sneks are kinda just a toy for now, they won't be part of the final lore. Code will be used for nasties in the ocean map though, probably some kinda smart eel monster.

**Comment by Nienhaus** [comment]
:+1: x :100:

**Comment by Zuhayr** [comment]
COME ON TRAVIS. This new indentation checker is really anal retentive.

**Comment by Zuhayr** [comment]
I have no idea what that bloody script was getting stuck on but it seems like it was in a comment.

**Pull request merged**
