### PR TITLE
Fixes, optimizations, prep work for mecha rewrite.

### PR DESCRIPTION
**Pull request by Zuhayr**
- Temporarily removes mechs completely from the game. They will be readded when the rewrite is done.
- Replaces some in world with in \<more appropriate list\>. This has the upshot of dropping literally 30-40 seconds from the game initialization.
- Comments out xenoarch for the time being. 
- Fixes the title screen.

Quoting GN:
````
for(var/atom/movable/AM in world) 136 ds
for(var/atom/movable/AM in movable_list) 154 ds
for(var/A in movable_list) 96 ds
````

### CODE REVIEW

**Comment by Zuhayr** [comment]
Doing some testing before declaring this ready.

**Comment by Zuhayr** [comment]
Only issue with this that I can see so far is that for some reason tables no longer initialize at roundstart. Constructed tables do.

**Comment by Zuhayr** [comment]
all_movable_atoms could stand to be broken into more specific lists.

**Comment by PsiOmegaDelta** [comment]
I need to do this for Bay as well, it's yet another thing that's been on my todo list (it's getting scary).

**Pull request merged**
