### PR TITLE
Map changes

### PR DESCRIPTION
**Pull request by NobleCaos**
mining elevator no layer
mining refinery

### CODE REVIEW

**Comment by NobleCaos** [comment]
mining dock
Posted the wrong screenshot

**Comment by Dennok** [comment]
Mining machynery work right?

**Comment by NobleCaos** [comment]
What mining machinery are you talking about? Refinery?

**Comment by Zuhayr** [comment]
Why is the diff so screwy?

**Comment by NobleCaos** [comment]
Zuhayr I have no idea what you're talking about... nothing seems scewy to me

**Comment by Dennok** [comment]
Yes, refinery.

**Comment by Dennok** [comment]
machines can take wrong input/output markers

**Comment by NobleCaos** [comment]
I do believe so, it's a quick change if they're not.

**Pull request merged**
