### PR TITLE
Adds icons for the pants along with makes the khaki pants show up. 

### PR DESCRIPTION
**Pull request by Nienhaus**
Also adds a Sailor uniform.
ej48fhx

### CODE REVIEW

**Comment by Finalsong** [comment]
:+1: :100: for sailor's uniform.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Loganbacca** [comment]
Compiles and works as advertised :+1:

**Comment by Nienhaus** [comment]
I know how to pr well.

**Pull request merged**
