### PR TITLE
Byond 510

### LINKED ISSUE #350: Character starts blind
Mobs start with the blind overlay enabled in byond 510.

Tested the exact same build in 509 and the issue didn't occur.

### PR DESCRIPTION
**Pull request by Loganbacca**
Based on the work done by @neersighted for https://github.com/tgstation/-tg-station/pull/14981

 - Ported tg's fullscreen overlay system
 - Changes text procs to new native procs
 - Fixes #350 

The main difference is I haven't bothered porting the 509 defines (so no backwards compatibility). Also mob code nearly did my head in as it is quite different from tg.

### CODE REVIEW

**Comment by Zuhayr** [comment]
You are a wonderful, wonderful person and I love you.

Really stoked to start playing with planar lighting in 510.

**Comment by Zuhayr** [comment]
I am on the verge of passing out now or I'd review this and merge it, will get to it in the morning.

**Comment by neersighted** [comment]
510 is pretty great, but 1325 has blending/alpha bugs... Anyway, cheers!

**Comment by Zuhayr** [comment]
Fuck it, we're not going to be going live with this before 510 is released anyway. LET'S DO IT.

**Pull request merged**
