### PR TITLE
Splits walls into constructed and natural

### PR DESCRIPTION
**Pull request by EmperorJon**
- Splits simulated/wall into simulated/wall/constructed and simulated/wall/natural.
- Wall icon/material behaviour is in the base wall type, so this can be used by new "natural" walls.
- Replaces mineable mineral turfs with natural walls, so they blend/connect correctly and use a rock material-based edge.
- This means only natural walls can be mined and only constructed walls can be constructed/deconstructed, but both use the same icon and material system.
- Changes sandstone to limestone and makes the default natural rock wall a limestone wall.
- Adds a new set of rock sprites to wall_masks.dmi. Doors/reinforced/etc. not supported, because there's no way to do this for natural walls.

- [x] Check for repeated functionality
- [x] Fix/change natural and/or base wall explosion/destruction
- [x] Redo map changes

Note: this PR might mangle maps like Example-1/2 a bit, because we seem to have deleted some of their areas, plus one was DMM and one TGM. Personally I don't consider that a big deal for this PR because they need to be fixed, removed, updated, or whatever as appropriate anyway.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
Gunna #yolo this as the Travis PR will conflict with it. Travis PR will be the Official Merge And Review Policy start date.

**Comment by Spacemanspark** [comment]
Oh, huh, is Europa coming back to life?

**Comment by EmperorJon** [comment]
> Gunna #yolo this 

#yolo accepted. More testing and work needed to clean this up. Will maybe roll into a bit of a mining overhaul with a better-planned approach...

**Comment by MistakeNot4892** [comment]
@Spacemanspark just dicking around for now, if it goes anywhere it'll get a public debut.

**Comment by Spacemanspark** [comment]
Sweet deal, hopefully it does go somewhere!

**Pull request merged**
