### PR TITLE
Map changes, mining

### PR DESCRIPTION
**Pull request by NobleCaos**
Missing: APC and airlock control.

### CODE REVIEW

**Comment by NobleCaos** [comment]
mining elevator
mining elevator no layer

**Comment by WrongEnd** [comment]
:+1:
I'll handle the airlock and power generation. Also, whoever it was who figured out the best way to configure a to-water airlock, tell me some time

**Comment by GinjaNinja32** [comment]
for now, just map in a closed chamber, same size as the first, doesn't need to be enterable but probably should be viewable. Preferably all airlocks will be 2x1 or larger, since there's two bits of machinery needed now.

**Comment by NobleCaos** [comment]
Where do you want that closed chamber, GinjaNinja32?

**Comment by NobleCaos** [comment]
mining outpost 13
Area is pulled over. Mining EVA.

**Pull request merged**
