### PR TITLE
Look and feel updates.

### PR DESCRIPTION
**Pull request by MistakeNot4892**
- Changes colours of browser popups from green/blue to orange/grey-blue.
- Changes NanoUI backgrounds to use the terminal graphics from oldEuropa.
- Removes NT and syndicate logos.

TODO:
- [X] Finish tweaking NanoUI text colours.
- [X] Make the NanoUI background mask work nicer with the new graphics.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
image
Ready for review.

**Comment by Lohikar** [comment]
Did you delete the reference to the syndie background in nano's JS?

**Comment by MistakeNot4892** [comment]
No, why?

**Comment by Lohikar** [comment]
You probably should, given that you're deleting that asset.

**Comment by MistakeNot4892** [comment]
No I'm not.

**Pull request merged**
