### PR TITLE
Deepsea Rig + Various sprites

### PR DESCRIPTION
**Pull request by SkowronX**
- [x] Deepsea Industrial Rig for abyssal mining.
deepsuit

- [x] Directional Windows and Reinforced windows
window and grille

- [ ] Full size window sprites.

- [x] Girder base
f9fc2c0126eedd05d75b7a8ece0b092c

- [ ] Displaced and damaged sprites

- [x] Abyssal canyon rockwall + black void

c9a3bcd1d08b9d62fabd10e30c36f108

### CODE REVIEW

**Comment by Zuhayr** [comment]
Pics?

**Comment by GinjaNinja32** [comment]
looks like you have
```
- a
- [ ] a
```
if you use
```
- [x] a
- [ ] a
```
it'll look like this:
- [x] a
- [ ] a

**Comment by SkowronX** [comment]
updated

**Comment by Zuhayr** [comment]
New object definitions need to go in code/modules/europa. I really should add that to contributing.md

**Comment by Zuhayr** [comment]
:+1:

**Comment by WrongEnd** [comment]
:+1:

**Comment by PJB3005** [comment]
:+1:

**Comment by Zuhayr** [comment]
:+1::+1::+1::+1::+1::+1:

**Pull request merged**
