### PR TITLE
Sign palette change and sign grime

### PR DESCRIPTION
**Pull request by Flatgub**
The blue rectangular signs have been changed to the new palette.
NewSigns

Rectangular signs now have an 80% chance to have a random grime overlay applied to them.
SignGrime

### CODE REVIEW

**Comment by Finalsong** [comment]
Pretty.

**Comment by SkowronX** [comment]
Nice

**Comment by NobleCaos** [comment]
Nice work, love the metroid Xenos sign.

**Comment by Techhead0** [comment]
I... I thought the Metroid was a Skrell.

**Pull request merged**
